### ISSUE TITLE
Debugging contracts

### ISSUE THREAD

**Issue by xermicus** [paritytech/revive#17]
We will have some means of debugging contract execution, likely via traces. This might require the compiler to produce debug information.

**Comment by Jan-Jan** [comment]
When I attempt to debug a successful deployment of a Solidity smart contract to Westend in Remix (as per [tutorial](https://contracts.polkadot.io/deploy-your-first-contract)), then I get the error message `Returned error: The method "debug_traceTransaction" does not exist / is not available.`. Is that part of the scope of this bug, or should a new one be filed?

**Comment by xermicus** [comment]
Thanks for asking, `debug_traceTransaction` is an RPC method. Debug information in the contract blob is not required for execution traces and replays.

**Comment by xermicus** [comment]
https://github.com/paritytech/contract-issues/issues/6

**Comment by athei** [comment]
Yes,  `debug_traceTransaction` is planned as it is needed for etherscan. @pgherveou is working on this.

**Comment by xermicus** [comment]
Closed by #118: Basic debug info is now emitted and will be reflected in the PVM blob.
