### ISSUE TITLE
Rename fields in contracts metadata 

### ISSUE THREAD

**Issue by smiasojed** [paritytech/revive#50]
In the metadata we provide following informations:
```
						"solc_zkvm_edition": null,
						"zk_version": "0.1.0"
```
I suppose we should change it to `revive_version`/`resolc_version`

**Comment by athei** [comment]
Isn't `resolc`= `revive`? So it should be `solc_version` and `revive_version`?

**Comment by smiasojed** [comment]
it is the same, I am not sure which convention we should follow `resolc` or `revive`.
solc has its own metadata:
`"solc_metadata": "{\"compiler\":{\"version\":\"0.8.26+commit.8a97fa7a\"},...}`

**Comment by xermicus** [comment]
`revive` is the project and workspace name and `resolc` the binary name of the Solidity frontend (matter labs names them in a similar fasion: "era compiler" is the overall compiler project name and `zksolc` the _Solidity_ frontend binary). We could add more frontends if needed, for example Vyper, or potentially some other binaries, which would still belong and live in `revive`.

We should rename those fields too:
`zk_version` -> `revive_version`
`solc_zkvm_edition` -> `pallet_revive_version`

**Comment by xermicus** [comment]
> Isn't `resolc`= `revive`? So it should be `solc_version` and `revive_version`?

As for the version, this should hold up. E.g. the `revive` version will dictate the `resolc` version anyways.
