### ISSUE TITLE
Remix expects the bytecode to not be null.

### ISSUE THREAD

**Issue by smiasojed** [paritytech/revive#51]
Remix expects the `evm.bytecode` to not be null in json output.
current format:
```
					"evm": {
						"legacyAssembly": null,
						"assembly": null,
						"bytecode": null,
						"deployedBytecode": {
							"object": ""
						},
						"methodIdentifiers": {}
					},
```				
expected:
```
					"evm": {
						"legacyAssembly": null,
						"assembly": null,
						"bytecode": :{
							"object": ""
						},,
						"deployedBytecode": {
							"object": ""
						},
						"methodIdentifiers": {}
					},
```

**Comment by xermicus** [comment]
Is this still the cases on latest `main`?

**Comment by xermicus** [comment]
I guess what we want to do instead is skipping serialization of any field if it isn't present. Remix expecting an empty string when it wasn't provided doesn't seem right. @smiasojed I implemented that [in this in a branch](https://github.com/paritytech/revive/tree/cl/std-json-serialize), does that help?

**Comment by smiasojed** [comment]
it looks that I do not observe this on the `main` branch anymore.

**Comment by smiasojed** [comment]
Closing as I can not reproduce it anymore.
