### ISSUE TITLE
Support the `extcodehash` opcode

### ISSUE THREAD

**Issue by xermicus** [paritytech/revive#63]
Needs a supporting API method in the pallet.

**Comment by xermicus** [comment]
Assigned to @ermalkaleci

**Comment by xermicus** [comment]
To be more precise, check the comments in #77:

@ermalkaleci The pallet should be changed to write the zero hash if the account exists but has no code, and all zeroes if the account was not found. The status code can then either be removed (since the callee can check it by inspecting the output buffer after the call value) or changed to reflect what exactly was written accordingly.

**Comment by ermalkaleci** [comment]
@xermicus this is resolved

**Comment by xermicus** [comment]
Thank you!
