### ISSUE TITLE
Incorrect JSON format of `solc_metadata`

### ISSUE THREAD

**Issue by smiasojed** [paritytech/revive#92]
Remix expects `contract.object.metadata` to be a string, but received a JSON object with `solc_metadata` inside as a string.
```
{
contract: {
"solc_metadata":"{\"compiler\":{\"version\":\"0.8.26+commit.8a97fa7a\"},\"language\"..."},
"solc_version": "0.8.26",
"solc_zkvm_edition": null,
"zk_version": "0.1.0"
}
```

**Comment by smiasojed** [comment]
Fixed on on remix side

**Comment by xermicus** [comment]
I'll keep this open for now. I assume we should deliver what remix expects, since other tool probably will expect the same? I feel like this might be consistently wrong, not only `solc_metadata` (probably remix just ignores other fields).

**Comment by smiasojed** [comment]
The issue is that Remix expects `contract.object.metadata` as a string, but it received a JSON object that contains `solc_metadata` as a string. The format of `solc_metadata` is correct, and I provided Remix with `contract.object.metadata.solc_metadata`, instead of `contract.object.metadata` which make sense here I think.
I think that it is not revive issue.

I also updated the issue description as it was wrong

**Comment by xermicus** [comment]
Ah okay I see. Thanks for clarifying. Yeah this is how I see in `solc` std json output directly:

` "metadata": "{\"compiler\":{\"version\":\"0.8.28+commit.7893614a\"},\"language\":\".....` 


So we just pass it through as `solc_metadata` as is. Thanks!
